### ISSUE TITLE
PostgreSQL/MariaDB provided database fails with 'FATAL: database "null" does not exist'

### ISSUE THREAD

**Issue by berndgoetz** [kubernetes-sigs/minibroker#117]
I'm using minbroker on kubecf, installed as follows:

```
helm repo add minibroker https://minibroker.blob.core.windows.net/charts 
kubectl create namespace minibroker 
helm install minibroker --namespace minibroker --set "deployServiceCatalog=false" --set "defaultNamespace=minibroker" minibroker/minibroker
```

My application is bound to the database with the following variables:

```
 "VCAP_SERVICES": {                                                                                                 
  "postgresql": [                                                                                                   
   {                                                                                                                
    "binding_name": null,                                                                                           
    "credentials": {                                                                                                
     "database": "",                                                                                                
     "host": "postgresql-4141dd8b527947166d76.minibroker.svc.cluster.local",                                        
     "password": "x",                                                                                      
     "port": 5432,                                                                                                  
     "postgresql-password": "x",                                                                           
     "protocol": "postgresql",                                                                                      
     "uri": "postgresql://postgres:x@postgresql-4141dd8b527947166d76.minibroker.svc.cluster.local:5432",   
     "username": "postgres"                                                                                         
    },      
...                                                                                                        
```

Trying the same with MariaDB yields the same result:

```
 "VCAP_SERVICES": {                                                                                      
  "mariadb": [                                                                                           
   {                                                                                                     
    "binding_name": null,                                                                                
    "credentials": {                                                                                     
     "database": "",                                                                                     
     "host": "mariadb-5883244b3a7a4716e4c1.minibroker.svc.cluster.local",                                
     "mariadb-replication-password": "x",                                                       
     "mariadb-root-password": "x",                                                              
     "password": "x",                                                                           
     "port": 3306,                                                                                       
     "protocol": "mysql",                                                                                
     "uri": "mysql://root:x@mariadb-5883244b3a7a4716e4c1.minibroker.svc.cluster.local:3306",    
     "username": "root"                                                                                  
    },                                                                                                   
...
```

As you can see, the database attribute is empty, and that results in the error at application startup:

```
08:35:42.918: [APP/PROC/WEB.0] 2020-11-15 07:35:42.916  INFO 6 --- [           main] c.s.t.config.CloudDatabaseConfiguration  : Configuring JDBC datasource from a cloud provider
08:35:44.582: [APP/PROC/WEB.0] 2020-11-15 07:35:44.577 ERROR 6 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.
08:35:44.582: [APP/PROC/WEB.0] org.postgresql.util.PSQLException: FATAL: database "null" does not exist
```

How do I make minibroker create and provide a database when creating the service? Thanks.

**Comment by bdekany** [comment]
Hi
When creating the service (from cli or Stratos) you have to specifiy the database name via a JSON argument.
Example for mairadb `cf create-service mariadb 10-1-34 my-db -c '{"db":{"name":"mydb"}}'`

**Comment by f0rmiga** [comment]
@bdekany Thanks for responding.
@berndgoetz Let me know if this solves your issue.

**Comment by berndgoetz** [comment]
Yes, that works. Many thanks! Troy Topnik pointed me to another solution: To define/fix the parameters in the minibroker configuration at setup time, e.g. as follows:

```
provisioning: 
  mariadb:
    overrideParams:
      db:
        user: "dbuser"
        name: "default"
      replication:
        enabled: false
      metrics:
        enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
  postgresql:
    overrideParams:
      postgresqlUsername: "dbuser"
      postgresqlDatabase: "default"
      replication:
        enabled: false
      metrics:
        enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
```

That's even more elegant and safe than with the -c parameter passing.
